name: Render and Publish Quarto Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Quarto from the .deb file stored in the repo
      - name: Install Quarto from local file
        run: |
          sudo apt-get update
          sudo apt-get install -y ./quarto-1.5.57-linux-arm64.deb

      # Render the Quarto Project
      - name: Render Quarto Project
        run: quarto render

      # Initialize gh-pages branch if it does not exist
      - name: Initialize gh-pages Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages || true
          git reset --hard
          git commit --allow-empty -m "Initialize gh-pages branch"
          git push origin gh-pages

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
